Feature/#48/acollow/pm
GEOS-ESM/GMAOpyobs pull request #49
Opened 2024-04-19 18:25 UTC by acollow

aop.py was modified to add in a class that allows for the calculation of particulate matter at a user provided threshold and relative humidity. Optics files are used to account for the growth of particles with humidity. mietable.py also changed as the ability to grab the bin radius was needed. This addresses and closes issue #48.

The option to run the extinction class at a set relative humidity was also added.

2024-08-14 16:28 UTC, patricia-nasa requested changes

2024-08-14 16:28 UTC, patricia-nasa commented on src/pyobs/aop.py
> +                rhod_ = self.mieTable[s]['rhod'][bin-1]
add some comments that explain what each of these variables is, and why you're scaling by 1e6

2024-08-14 16:28 UTC, patricia-nasa commented on src/pyobs/aop.py
> +                    rLow_ = rLow_ * np.sqrt((rhod_/1000)/self.mieTable[s]['shapefactor'])
add a comment here that explains what shapefactor represents

2024-08-14 16:28 UTC, patricia-nasa commented on src/pyobs/aop.py
> +                    rLow_ = rLow_ * np.sqrt((rhod_/1000)/self.mieTable[s]['shapefactor'])
i'm confused about what units you're using here.  why is rhod_ being divided by 1000?

2024-08-14 16:28 UTC, patricia-nasa commented on src/pyobs/aop.py
> +
here you can put a check:
```
if rPM is None:
     fPM = 1.0. # adding everything
else:
     do your other checks here
```

2024-08-14 16:28 UTC, patricia-nasa commented on src/pyobs/aop.py
> +            ds = g.getPM(wavelength=w,pmsize=options.d_pm,fixrh=options.fixrh,aerodynamic=options.aerodynamic)
remove wavelength here.  it's not used.

2024-08-14 16:28 UTC, patricia-nasa commented on src/pyobs/aop.py
> +    #rts = None # g.getAOPrt(wavelength=550,vector=False)
why did you take out the other examples. you should add yours to the already existing examples.

2024-08-14 16:28 UTC, patricia-nasa commented on src/pyobs/mietable.py
> +      rUp              (b) Dry lower radius [m]
I think this is a typo.  rLow is the lower radius, rUp is the upper radius

2024-08-14 16:29 UTC, patricia-nasa commented
can you resolve the conflict before the next PR.

2024-08-14 19:46 UTC, acollow commented on src/pyobs/aop.py
> +    def getPM(self,Species=None,wavelength=None,pmsize=None,fixrh=None,aerodynamic=False):
A dummy wavelength is needed to use mie.getAOP to find the effective radius.

2024-08-14 20:09 UTC, patricia-nasa commented on src/pyobs/aop.py
> +    def getPM(self,Species=None,wavelength=None,pmsize=None,fixrh=None,aerodynamic=False):
it shouldn't require it.  if it does, then mietables.py needs to be fixed.

2024-08-14 20:22 UTC, acollow commented on src/pyobs/aop.py
> +    def getPM(self,Species=None,wavelength=None,pmsize=None,fixrh=None,aerodynamic=False):
Fair point, we could take rMass and rEff out of getAOP and put in a new function to get those with just bin and RH as the input.

2024-08-15 13:47 UTC, patricia-nasa commented on src/pyobs/aop.py
> +    def getPM(self,Species=None,wavelength=None,pmsize=None,fixrh=None,aerodynamic=False):
not necessary.  getAOP already doesn't require wavelength.  if for some reason it's not working for the rEff and rMass case then just fix that.

2024-08-16 13:48 UTC, patricia-nasa approved these changes
Looks good.

2024-08-16 13:48 UTC, merged